  name: Push the Docker image to AWS ECR Repo
  on:
    push:
      branches:
        - main
  jobs:
    docker-build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Configure AWS Credentials 
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-region: ${{ secrets.AWS_REGION }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build and push
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: ${{ secrets.REPOSITORY }}
            IMAGE_TAG: ${{ github.sha }}
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ${{ env.REGISTRY}}/${{ env.REPOSITORY}}:${{ env.IMAGE_TAG}}